project-codeflare/codeflare-cli

bin/codeflare, plugins/plugin-madwizard/src/plugin.ts
1) was not finding mirrored/packaged store for production builds
2) production builds not located in /Applications or /usr/local would default to those locations
3) -c -> -u i.e. default to CLI operation
=> fix: codeflare launcher fixes for store location

package-lock.json, plugins/plugin-madwizard/package.json, tests/plugin-madwizard/markdowns/guidebook-tree-model1.md, tests/plugin-madwizard/markdowns/guidebook-tree-model2.md, tests/plugin-madwizard/markdowns/guidebook-tree-model3.md, tests/plugin-madwizard/markdowns/guidebook-tree-model4.md, tests/plugin-madwizard/markdowns/guidebook-tree-model5.md, tests/plugin-madwizard/markdowns/guidebook-tree-model6.md, tests/plugin-madwizard/markdowns/guidebook-tree-model7.md, tests/plugin-madwizard/markdowns/snippets/importaa.md, tests/plugin-madwizard/markdowns/snippets/importd.md, tests/plugin-madwizard/markdowns/snippets/importdd.md, tests/plugin-madwizard/markdowns/snippets/importf.md, tests/plugin-madwizard/markdowns/snippets/importgg.md, tests/plugin-madwizard/markdowns/snippets/snippets-in-tab0.md, tests/plugin-madwizard/markdowns/snippets/snippets-in-tab0a.md, tests/plugin-madwizard/markdowns/snippets/snippets-in-tab0b.md, tests/plugin-madwizard/markdowns/snippets/snippets-in-tab1.md, tests/plugin-madwizard/markdowns/snippets/snippets-in-tab1a.md, tests/plugin-madwizard/markdowns/snippets/snippets-in-tab1b.md, tests/plugin-madwizard/markdowns/snippets/snippets-in-tab2.md, tests/plugin-madwizard/markdowns/snippets/snippets-in-tab3.md, tests/plugin-madwizard/markdowns/snippets/snippets-in-tab3a.md, tests/plugin-madwizard/markdowns/snippets/snippets-in-tab4.md, tests/plugin-madwizard/markdowns/snippets/snippets-in-tab5.md, tests/plugin-madwizard/markdowns/snippets/snippets-in-tab5c.md, tests/plugin-madwizard/markdowns/snippets/snippets-in-tab6.md
This includes the breaking change from madwizard: guidebook relative imports now need to use a `./` or `../` prefix to indicate that they are relative (rather than store-absolute) references.
=> chore: update to madwizard 0.9.0

plugins/plugin-madwizard/src/plugin.ts, plugins/plugin-madwizard/src/read.ts
Try to load just the madwizard/cli, rather than all of madwizard (which loads lots of stuff we don't need for the initial execution in headless mode). It's possible that webpack has already optimized this away, but it's a small enough change...
This PR also updates the Guide.tsx component to avoid calling an internal API of madwizard/Parser
=> fix: small optimization for initial load time of `guide` command

bin/codeflare, plugins/plugin-codeflare/src/plugin.ts, plugins/plugin-madwizard/src/plugin.ts
we should play ml/codeflare by default, if the user does not specify a guidebook to run.
=> fix: codeflare cli should have a default guidebook

bin/codeflare, plugins/plugin-madwizard/src/plugin.ts
```shell
codeflare -V ml/codeflare
```
the -V needs to be at the beginning
=> fix: support passing through -V verbose flag to madwizard

plugins/plugin-client-default/src/index.tsx, tests/common/startElectron.ts, tests/plugin-codeflare/dashboard/dashboard.ts, tests/plugin-codeflare/dashboard/inputs/1.spec.ts
we had a handful of commits where husky was not enabled, and so formatting was not performed
=> chore: run `npm run format`

package-lock.json, package.json, plugins/plugin-client-default/notebooks/dashboard.md, plugins/plugin-codeflare/src/components/GPUChart.tsx, plugins/plugin-codeflare/src/controller/chart.ts, plugins/plugin-codeflare/src/types.ts
There will now be a `chart <path/to/gpu.txt>` command.
The dashboard.md has been updated to use that command, instead of showing the raw text file.
Closes #123
=> feat: Add initial codeflare gpu utilization chart command setup

plugins/plugin-codeflare/web/scss/components/Dashboard/Charts.scss
=> fix: chart title should be sans-serif

plugins/plugin-client-default/config.d/style.json, plugins/plugin-codeflare/src/components/Chart.tsx, plugins/plugin-codeflare/web/scss/components/Dashboard/Charts.scss
the Tile title font does not scale, whereas the fonts in the chart do...
=> fix: back off use of Tile wrapper around charts

plugins/plugin-codeflare/src/components/Chart.tsx, plugins/plugin-codeflare/web/scss/components/Dashboard/Charts.scss, plugins/plugin-codeflare/web/scss/components/Dashboard/_index.scss
=> fix: yet more chart layout tweaks

plugins/plugin-codeflare/src/components/Chart.tsx, plugins/plugin-codeflare/web/scss/components/Dashboard/_index.scss
the height of the lower right split changes momentarily (as presumably monaco-editor loads for the first time)
=> fix: first switch to Application source results in odd glitch

plugins/plugin-codeflare/src/components/Terminal.tsx, plugins/plugin-codeflare/src/controller/tailf.ts
we should just pass the raw buffer data directly to the xterm, so that it can handle cursor motion properly. e.g. moving cursors to previous lines, deleting lines...
=> fix: dashboard Application Logs tail -f incorrectly splits newlines

package-lock.json, plugins/plugin-codeflare/package.json, plugins/plugin-codeflare/src/components/Terminal.tsx, plugins/plugin-codeflare/web/scss/components/Terminal/_index.scss, plugins/plugin-codeflare/web/scss/components/Terminal/_mixins.scss
This PR introduces a search box below the application logs. It allows for searching.
Fixes #179 
Though that issue asks for filtering, and this provides search capability, I'll close that issue, for now. In order to do filtering, we would need to write an xterm.js addon. There is already an `xterm-addon-search`, but no `xterm-addon-filter`. See: https://github.com/xtermjs/xterm.js/tree/master/addons
=> feat: Terminal content search feature

plugins/plugin-codeflare/src/components/Chart.tsx
We need to override more of the PatternFly legend tooltip bits. We already are, but are missing a few places.
Why? see https://github.com/patternfly/patternfly-react/issues/7633
=> fix: chart tooltips can be too wide

bin/codeflare
We needed this while we were using `listr2`. As we no longer use `listr2`, this hack is no longer needed.
=> fix: remove `stty sane` from bin/codeflare launcher

bin/codeflare, package-lock.json, package.json, plugins/plugin-codeflare/package.json, plugins/plugin-codeflare/src/controller/attach.ts, plugins/plugin-codeflare/src/controller/index.ts
This command executes the `ml/ray/aggregator` guidebook, and then launches the dashboard against the aggregator's staging directory.
TODO: the underlying aggregator guidebooks are still teeing to the console. We need to inhibit this somehow.
=> feat: codeflare attach command

plugins/plugin-codeflare/src/tray.ts
=> fix: tray menu support gives command an exception in headless mode

bin/codeflare, package.json, plugins/plugin-client-default/notebooks/dashboard-summary.md, plugins/plugin-client-default/notebooks/dashboard.md, plugins/plugin-client-default/src/index.tsx, plugins/plugin-codeflare/src/controller/catchall.ts, plugins/plugin-codeflare/src/controller/charts/all.tsx, plugins/plugin-codeflare/src/controller/charts/gpu.tsx, plugins/plugin-codeflare/src/controller/charts/index.ts, plugins/plugin-codeflare/src/controller/charts/vmstat.tsx, plugins/plugin-codeflare/src/controller/dashboard.ts, plugins/plugin-codeflare/src/controller/description.ts, plugins/plugin-codeflare/src/controller/events/Events.tsx, plugins/plugin-codeflare/src/controller/events/index.ts, plugins/plugin-codeflare/src/controller/index.ts, plugins/plugin-madwizard/src/plugin.ts
Push this complexity to a kui catchall command registration. We want `codeflare ml/codeflare` to open in guide mode. We do this, in this PR, by using a Kui catchall, catching all unknown command lines that start with `codeflare ...`. With this in place, we can remove some of the junk in the bin/codeflare shell script.
This PR also fixes a number of bugs with handling of spaces in filepaths. Why add this to this PR? Because we need to update bin/codeflare to use "$@" to fix spaces... This requires us to add `codeflare ` as a prefix, which leads to the catchall ...
=> chore: code cleanup to avoid too much magic in the bin/codeflare shell script

plugins/plugin-client-default/web/scss/components/Client.scss
we are using kui's default `var(--color-text-02)`
=> fix: header text should be darker and bigger

plugins/plugin-codeflare/src/controller/catchall.ts, plugins/plugin-codeflare/src/controller/index.ts
Oof, our filter was checking argv[1]===codeflare, instead of argv[0]
=> fix: codeflare catchall does not fire

bin/codeflare, plugins/plugin-codeflare/src/controller/attach.ts, plugins/plugin-madwizard/src/plugin.ts
We have been using `-a` to mean two things: --auto as in non-interactive guide run, and also `-a` to mean "attach" for dashboard operations. This makes it impossible to attach a dashboard in non-interactive mode.
=> feat: change --auto to --yes

plugins/plugin-codeflare/src/tray/menus/index.ts, plugins/plugin-codeflare/src/tray/menus/profiles.ts, plugins/plugin-codeflare/src/tray/menus/runs.ts
This PR flattens the list of profiles into the top-level menu, and the list of runs for a profile into that profile's menu. It also adds a missing copyright header to tray/menus/runs.ts
=> feat: flatten the tray menu a bit

plugins/plugin-codeflare/src/tray/watchers/profile/status.ts
This is mostly for debugging, i.e. showing the output of the subprocess kills. So we should emit it to the debug stream.
=> fix: when killing profile status watcher, log to debug

plugins/plugin-codeflare/src/tray/menus/profiles/boot.ts, plugins/plugin-codeflare/src/tray/menus/profiles/index.ts, plugins/plugin-codeflare/src/tray/menus/profiles/runs.ts, plugins/plugin-codeflare/src/tray/menus/profiles/shutdown.ts
- place boot and shutdown at the top
- add a Status "header" to the Head x/y Worker x/y section
=> feat: some minor cleanups to the tray profiles menu layout and source

plugins/plugin-codeflare/src/controller/respawn.ts
this can result in random files (such as .kube/cache) appearing in your CWD
=> fix: tray-launched subprocesses have no HOME

package-lock.json, package.json, plugins/plugin-codeflare/src/controller/index.ts, plugins/plugin-codeflare/src/tray/menus/profiles/dashboards/index.ts, plugins/plugin-codeflare/src/tray/menus/profiles/dashboards/mlflow.ts, plugins/plugin-codeflare/src/tray/menus/profiles/index.ts, plugins/plugin-codeflare/src/tray/menus/profiles/runs.ts, plugins/plugin-codeflare/src/tray/menus/section.ts
This menu item uses the ml/ray/start/kubernetes/port-forward/mlflow guidebook to set up a port forward to the mlflow service started by the codeflare ray helm chart. It opens a kui window to localhost:thatPort, and then tears down the port-forward when the user closes that popup window.
=> feat: add Dashboard tray menu, with MLFlow entry

bin/codeflare, package-lock.json, plugins/plugin-madwizard/package.json, plugins/plugin-madwizard/src/plugin.ts
Also: bump to madwizard 0.15.7 to pick up profile fix
codeflare -p myprofile, the desired myprofile was not used in all cases by madwizard in its subprocess executions
=> feat: expose `-p/--profile` option to start a run with a desired profile

plugins/plugin-codeflare/src/tray/menus/profiles/dashboards/codeflare.ts
for now, at least. it would be nice if we could detect whether a job is running, and only follow running jobs... until we have that kind of capability, we need to follow everything...
=> fix: tray dashboard popups should be in follow mode

plugins/plugin-codeflare/src/tray/watchers/profile/list.ts, plugins/plugin-codeflare/src/tray/watchers/profile/run.ts
two separate small bugs. on the former, it turns out that chokidar's `depth` option starts at 1, and we were passing 0. on the latter, we had a copy-paste bug, and were pushing on both the addDir and unlink events.
=> fix: tray runs watch still adds garbage, and does not respond to deletion

plugins/plugin-codeflare/src/tray/watchers/profile/list.ts, plugins/plugin-codeflare/src/tray/watchers/profile/run.ts
It looks like if we don't close the chokidar watchers before exit, the electron main process dies with SIGABRT.
=> fix: electron crashes with SIGABRT on quit

plugins/plugin-codeflare/src/tray/menus/profiles/runs.ts
we are slicing prior to sorting! which means the latest runs may be sliced off...
=> fix: latest runs may not show up in tray menu

plugins/plugin-codeflare/src/tray/main.ts
this helps with the "x seconds ago" menu item labels
=> fix: periodically rescan the tray menu

plugins/plugin-codeflare/src/tray/menus/profiles/shutdown.ts
Previously, we were hard-coding a kubernetes shutdown.
=> feat: update tray shutdown handler to use new ml/ray/stop guidebook

package-lock.json, plugins/plugin-madwizard/package.json
This gives us support for pre-generating the parsed ASTs for the guidebooks, and loading those instead of doing a full parse from source every time a user runs a guidebook.
This should happen transparently, by virtue of running `npm run mirror`
=> fix: bump to madwizard 0.17.1 to pick up load time optimizations

plugins/plugin-client-default/notebooks/hello.md, plugins/plugin-codeflare/src/controller/profile/get.tsx, plugins/plugin-codeflare/web/scss/components/Hello/_index.scss
- profiles now have an icon and subtext
- new profile tile
clicks still do nothing (TODO)
=> feat: more refinements to the hello component

plugins/plugin-client-default/notebooks/hello.md, plugins/plugin-codeflare/src/controller/terminal.tsx
This PR also updates hello.md to use `codeflare terminal $SHELL -l`, i.e. adding the `-l` part to ensure that we are launching a login shell. That change needed the fix to handle command lines with options...
=> fix: `codeflare terminal` does not handle command lines with options

plugins/plugin-codeflare/src/components/ProfileExplorer.tsx, plugins/plugin-codeflare/web/scss/components/Hello/_index.scss
This PR also fixes a problem with the grid-template-columns of the profiles, by switching from a auto-fill to auto-fit. This makes sure that our `max-content` sizing gives less overflow.
=> feat: in hello.md, move profiles to the top

plugins/plugin-client-default/notebooks/about.md, plugins/plugin-client-default/notebooks/hello.md, plugins/plugin-client-default/src/CodeFlareWidget.tsx
I think can we can show this instead to first-timers in a modal popup (TODO).
This PR also updates the CodeFlareWidget text to use the same content as we have in the welcome markdown.
=> feat: move hello welcome content to a separate markdown file

plugins/plugin-codeflare/src/components/RestartableTerminal.tsx
if we have yet to start a terminal pty job, the componentWillUnmount gets a null pointer exception
=> fix: switching profiles in profileexplorer may result in Internal Error

plugins/plugin-codeflare/src/controller/index.ts
this PR restores the `codeflare hello` command, and also adds `codeflare explorer`, which both launch the same command handler as the existing `codeflare explore`
=> fix: `npm run open` is broken

deploy/log-aggregator/Dockerfile, deploy/log-aggregator/wait-for.sh
We are setting a USER in our Dockerfile that does not seem to work with containers secured by a SELinux host.
=> fix: log aggregator may fail in restricted docker hosts

package-lock.json, package.json
This picks up some in-kube-cluster support for ray
=> chore: bump to @guidebooks/store 0.3.0

plugins/plugin-codeflare/src/controller/attach.ts, plugins/plugin-codeflare/src/controller/description.ts, plugins/plugin-codeflare/src/controller/run/get.ts, plugins/plugin-codeflare/src/controller/status.ts, plugins/plugin-codeflare/src/tray/menus/profiles/active-runs.ts, plugins/plugin-codeflare/src/tray/watchers/profile/active-runs.ts
Instead of showing nothing for an extended period of time, we now open a window immediately and show some (for now textual) progress info.
This PR also fixes some issues that could result in bogus output (`cannot read property runtime_env of undefined`) in job description.
=> fix: improved UX for attaching to running jobs

package-lock.json, plugins/plugin-codeflare/package.json, plugins/plugin-madwizard/package.json
picks up a bug fix for showing emacs temporaries in the profiles menu
also a few other minor bumps (allotment 1.15 -> 1.16)
=> chore: bump madwizard 0.19.3 -> 0.19.4

Casks/bump.sh, Casks/codeflare.tpl, package.json
We were using before:release, but it should be after:bump. Also, our cask bump.sh script was not templating in the new version.
=> fix: release-it does not correctly publish cask updates

package.json
Weird, we are using `$version`, but it appears that release-it requires this to be `${version}`
=> fix: release-it is not propagating version

deploy/self-test/roberta/1gpu/periodic.yaml
we had them under the job template, and for some reason kubectl did not complain about a schematic error
=> fix: roberta self-test cronjob does not properly specify history limit specs

bin/codeflare, plugins/plugin-madwizard/src/plugin.ts
It does not support long-form options. I think we did this originally, because we were (originally) calling to the madwizard npm directly from the bin/codeflare shell script launcher.
=> fix: stop using getopts in bin/codeflare

plugins/plugin-codeflare/src/tray/main.ts, plugins/plugin-codeflare/src/tray/watchers/profile/status.ts
i think this actually is a problem whenever there are errors in some of the tray watchers. but it is also possible that on macos the problem is masked by the OS.
the fix for linux is to self-manage needless repaints, by only calling the tray setContextMenu api when there are changes. sigh.
=> fix: avoid tray menu "blinking" on linux

plugins/plugin-codeflare/src/tray/icons.ts, plugins/plugin-codeflare/src/tray/main.ts
We had two places in the tray menu code where we were assuming the macOS file layout for production builds (which is somewhat different from that on linux and windows)
=> fix: tray menu does not appear in production builds on linux and windows

plugins/plugin-client-default/config.d/style.json
I don't know why we were using a frameless electron window. On macOS, all that is needed is
```
"titleBarStyle": "hiddenInset",
```
=> fix: no window close button on linux and windows

package.json
ugh, we did this before, but incorrectly. we had three fields named `out`, and prettier squashed them
=> chore: re-update package.json to bump roberta self-test image versions

package-lock.json, plugins/plugin-madwizard/package.json
It will now be `ml/codeflare/training/byoc`
=> chore: bump @guidebooks/store to 0.6.6 to pick up byot -> byoc renaming

package.json
We are trying to use `@release-it/bumper` to bump the image versions in some of our yaml files. These are multi-document yamls, which that bumper npm does not support due to https://github.com/release-it/bumper/issues/24.
For now, we will need to bump those versions manually.
=> fix: back out release-it bumper for yamls

deploy/self-test/roberta/1gpu/once.yaml, deploy/self-test/roberta/1gpu/periodic.yaml
We need to do this manually, for now. See https://github.com/project-codeflare/codeflare-cli/pull/533
=> chore: bump roberta self-test image versions

package-lock.json, plugins/plugin-madwizard/package.json
This also picks up `ml/codeflare/training/roberta/demo`
=> fix: bump to @guidebooks/store 0.7.2 to pick up roberta fix

package-lock.json, plugins/plugin-madwizard/package.json
- bump to @guidebooks/store 0.11.1, to pick up fixes for kubernetes/choose/ns, the option for creating a namespace.
- improvements to finding a local install of the `ray` CLI on macOS.
- lower defaults for ray cluster resource requests
=> fix: "create namespace" option causes odd failures

plugins/plugin-codeflare/src/controller/respawn.ts
I think this only affects macOS, for which chromium has a separate executable for the Renderer process.
=> fix: respawn uses incorrect (Renderer) executable when called from UI mode

plugins/plugin-client-default/config.d/client.json, plugins/plugin-madwizard/src/plugin.ts
This PR allows client plugins to specify the default guidebook in config.d/client "defaultGuidebook", e.g.
```json
{
"defaultGuidebook": "ml/codeflare"
}
```
=> fix: stop hard-coding default guidebook

plugins/plugin-codeflare/src/tray/watchers/profile/list.ts
We had a race condition in the chokidar file update handler.
=> fix: profiles in tray menu may show duplicates

plugins/plugin-codeflare/web/scss/components/ProfileExplorer/_index.scss
This PR also fixes a color contrast issue with the tree twisties in dark themes.
=> fix: use normal repl background color for ProfileExplorer

plugins/plugin-codeflare/src/components/ProfileExplorer.tsx
We removed the UI for this a while back, but forgot to remove the underlying status watcher process.
=> fix: fully disable profile status watcher

plugins/plugin-codeflare/src/components/Terminal.tsx
This takes up a few pixels of vertical space. In dark themes, it is also visible, despite having no functionality.
=> fix: Terminal component still has toolbar UI even when `searchable===false`

plugins/plugin-codeflare/src/components/Ask.tsx, plugins/plugin-codeflare/src/components/ProfileExplorer.tsx
In Ask, don't use card header "Configure". Use Hint for title. Place Home icon in Hint. Don't show filter for Select by default. Add filter toggle action to Hint. Add description to ui for choices.
In ProfileExplorer, don't use larger font size for action buttons.
=> fix: ui refinements to ProfileExplorer and Ask

plugins/plugin-codeflare/src/components/AskingTerminal.tsx
This also fixes a bug where we would force an unnecessary resize via the Allotment api on initial render.
=> fix: reduce default height of terminal portion

plugins/plugin-client-default/notebooks/hello.md, plugins/plugin-codeflare/src/controller/index.ts, plugins/plugin-codeflare/src/controller/terminal.tsx, plugins/plugin-codeflare/src/index.ts
we were already calling it that in src/index, i.e. the exported API of plugin-codeflare
=> chore: rename main UI component TaskTerminal -> WorkloadDesigner

package-lock.json, plugins/plugin-madwizard/package.json
That release of the store also includes switching ray from Deployment to Job, bumping mcad to pick up `completionstatus` support, and updating the helm charts to use that support.
=> feat: bump to @guidebooks/store@0.18.0 to pick up ray auto-stop

plugins/plugin-codeflare/src/tray/menus/profiles/index.ts
This can still cause high cpu consumption in cases where a kubernetes context is not reachable.
=> feat: disable status watching in tray menu

plugins/plugin-madwizard/components/src/WorkloadDesigner.tsx, plugins/plugin-madwizard/components/src/designer.tsx
e.g. via `workload designer --left 0
=> feat: allow WorkloadDesigner to hide ProfileExplorer

.github/workflows/kind.yml, package-lock.json, package.json, plugins/plugin-codeflare/package.json, tests/kind/profiles/non-gpu1/ray-autoscaler, tests/kind/run.sh
also: bump kui to pick up fix for -h/-v options, and also bump madwizard for that fix, too Fixes #791
BREAKING CHANGE: from `@guidebooks/store@5` remove ray autoscaler support (needed to make tests pass, since ray2 has some breakage that has gone undetected till now)
=> fix: bump kui to pick up fix for -h/-v options, and fix for ray head node label selector not being job-specific

package-lock.json, plugins/plugin-codeflare/package.json, plugins/plugin-codeflare/src/controller/index.ts, plugins/plugin-codeflare/src/controller/logs.ts, plugins/plugin-codeflare/src/controller/options.ts
https://github.com/guidebooks/store/pull/576
=> feat: bump to `@guidebooks/store@5.2.0` to pick up more flexible (non-ray) vmstat tracking

package-lock.json, plugins/plugin-codeflare/package.json
https://github.com/guidebooks/store/pull/608
That PR also updated the helm install for ray so as to avoid communicating the workdir as an env var
=> fix: helm install may fail on linux due to base64-induced newlines

package-lock.json, plugins/plugin-codeflare/package.json
This also should fix the warning that Winteractive is not a known option on linux/gnu awk.
=> feat: move cpu and memory utilization to be first column

.github/workflows/kind.yml, package-lock.json, plugins/plugin-codeflare/package.json
https://github.com/guidebooks/store/pull/634
if a Job does not specify parallelism=completions, then a livelock will occur. with the default parallelism (which is 1), the Job controller creates one Pod at a time, waiting till it is scheduled before creating the next one. meanwhile, the coscheduler doesn’t allow that first one to be scheduled until the rest of the Pods are created…
and … for ray, we were using Jobs with default parallelism
=> fix: ray helm chart should specify `parallelism` to avoid livelock

package-lock.json, plugins/plugin-codeflare/package.json
* helm workdir fails for relative paths ([1350e49](https://github.com/guidebooks/store/commit/1350e49674d38cc50e75522978e6bda643e768c6))
* we were looking for ERROR instead of FAILED for failed ray jobs ([8a4d332](https://github.com/guidebooks/store/commit/8a4d33268e15ec6cdd4c7cf1e6e3463facde9e3c))
* ray self-destruct should establish security context ([d6ed018](https://github.com/guidebooks/store/commit/d6ed01833b3c8ada8bb1be27abf6d36c3a74ae0a))
=> fix: helm workdir fails for relative paths; improved detection of ray job failure

package-lock.json, plugins/plugin-codeflare/package.json
* avoid use of -Winteractive on macos ([6a89cad](https://github.com/guidebooks/store/commit/6a89cad80665c0cafc314dbd7212914f64366209))
* gpu utilization may not be streamed out ([9925290](https://github.com/guidebooks/store/commit/9925290882ece9bbd7870d8e07046bcbfeb3d048))
* when looping kubectl events, use watch-only after first iter ([25a6511](https://github.com/guidebooks/store/commit/25a6511024e253bb3b955e2466fb4a9b508cb3ab))
=> fix: improved kubectl and gpu streaming

package-lock.json, plugins/plugin-codeflare/package.json
* improve handling of no aws profiles/no buckets situations ([30be07b](https://github.com/guidebooks/store/commit/30be07bf6fe3a86295cfd5b7ed0ebde76a91f08e))
* ml/codeflare/training/demos/getting-started/submit should offer submit-only ([e2da046](https://github.com/guidebooks/store/commit/e2da046492f908aef516daa2257a20bf01b63d80))
* improve handling of no aws profiles/no buckets situations ([30be07b](https://github.com/guidebooks/store/commit/30be07bf6fe3a86295cfd5b7ed0ebde76a91f08e))
* ml/codeflare/training/demos/getting-started/submit should offer submit-only ([e2da046](https://github.com/guidebooks/store/commit/e2da046492f908aef516daa2257a20bf01b63d80))
=> fix: improvements to s3 profile/bucket scanning

package-lock.json, package.json, plugins/plugin-codeflare/package.json, tests/kind/inputs/torchx/compute_world_size/main.py, tests/kind/profiles/non-gpu1/keep-it-simple, tests/kind/profiles/non-gpu1/mcad-coscheduler, tests/kind/profiles/non-gpu1/mcad-default, tests/kind/profiles/non-gpu1/mcad-preinstalled, tests/kind/profiles/non-gpu1/ray-autoscaler, tests/kind/profiles/non-gpu2/keep-it-simple, tests/kind/profiles/non-gpu3/keep-it-simple, tests/kind/profiles/non-gpu4/keep-it-simple, tests/kind/profiles/non-gpu5/keep-it-simple, tests/kind/run.sh
This PR also includes fixes for the tests, as for some reason the default ray python 3.7 image stopped working. THis PR updates to the python 3.8 images.
This PR also fixes support for running the tests on apple silicon (by using ray's 2.3.0-py38-aarch64 images; the x86 tests will continue, for now, to use 2.1.0-py38)
=> fix: pick up fix for profile import --force

package-lock.json, package.json, plugins/plugin-codeflare-dashboard/.gitignore, plugins/plugin-codeflare-dashboard/.npmignore, plugins/plugin-codeflare-dashboard/package.json, plugins/plugin-codeflare-dashboard/src/components/Dashboard.tsx, plugins/plugin-codeflare-dashboard/src/components/Dashboard/index.tsx, plugins/plugin-codeflare-dashboard/src/controller/dashboard/db.tsx, plugins/plugin-codeflare-dashboard/src/controller/dashboard/index.ts, plugins/plugin-codeflare-dashboard/src/controller/dashboard/kinds.ts, plugins/plugin-codeflare-dashboard/src/controller/dashboard/options.ts, plugins/plugin-codeflare-dashboard/src/controller/dashboard/status.tsx, plugins/plugin-codeflare-dashboard/src/controller/dashboard/tailf.ts, plugins/plugin-codeflare-dashboard/src/controller/dashboard/themes/status.ts, plugins/plugin-codeflare-dashboard/src/controller/dashboard/themes/utilization.ts, plugins/plugin-codeflare-dashboard/src/controller/dashboard/utilization.tsx, plugins/plugin-codeflare-dashboard/src/controller/dump.ts, plugins/plugin-codeflare-dashboard/src/index.ts, plugins/plugin-codeflare-dashboard/src/plugin.ts, plugins/plugin-codeflare-dashboard/tsconfig.json, plugins/plugin-codeflare/package.json, plugins/plugin-codeflare/src/controller/index.ts, tests/kind/profiles/non-gpu1/mcad-coscheduler.arm64, tests/kind/profiles/non-gpu1/mcad-coscheduler.x86_64, tests/kind/profiles/non-gpu1/mcad-default.arm64, tests/kind/profiles/non-gpu1/mcad-default.x86_64, tests/kind/profiles/non-gpu1/mcad-preinstalled.arm64, tests/kind/profiles/non-gpu1/mcad-preinstalled.x86_64, tsconfig.json
```shell
codeflare dashboard all|cpu|memory|status [jobId|-N]
```
if the last argument (jobId) is not supplied, the latest one in the given profile (`-p/--profile`) will be used. This is equivalent to supplying `-1` for the jobId positional; more generally, `-2` will fetch the penultimate, and `-N` will use the Nth-last job to be run in the profile.
you can get such a demo mode by running `codeflare dashboard all --demo`
- this currently assumes that the aggregator is already running against the job
- no gpu metrics, yet
This also adds some helpers:
```
codeflare dump logs|cpu|gpu|memory|status [jobId|-N]
```
which will dump out the raw logs, cpu stats, etc. the `jobId|-N` positional has the same interpretation as above.
=> feat: new console-based dashboard

plugins/plugin-codeflare-dashboard/src/components/Dashboard/index.tsx, plugins/plugin-codeflare-dashboard/src/controller/dashboard/db.tsx, plugins/plugin-codeflare-dashboard/src/controller/dashboard/index.ts, plugins/plugin-codeflare-dashboard/src/controller/dashboard/utilization.tsx
the `<Dashboard/>` component now supports `null` slots which mark row breaks in the grid-of-grids layout
```
[
gridFor("status"),
null, // newline
gridFor("cpu%"),
gridFor("mem%"),
gridFor("gpu%"),
gridFor("gpumem%"),
]
```
=> fix: support arranging dashboard grids into rows

plugins/plugin-codeflare-dashboard/src/controller/dashboard/grids.ts, plugins/plugin-codeflare-dashboard/src/controller/dashboard/index.ts, plugins/plugin-codeflare-dashboard/src/controller/dashboard/status.tsx, plugins/plugin-codeflare-dashboard/src/controller/dashboard/themes/status.ts, plugins/plugin-codeflare-dashboard/src/controller/dashboard/themes/utilization.ts
this also updates the utilization grids; rearrange into cpu, gpu, mem, gpumem, and keep some color correspondence between cpu-mem and gpu-gpumem
=> fix: use colorbrewer theme for status

package-lock.json, plugins/plugin-codeflare-dashboard/package.json, plugins/plugin-codeflare-dashboard/src/components/Dashboard/index.tsx, plugins/plugin-codeflare-dashboard/src/components/Dashboard/types.ts, plugins/plugin-codeflare-dashboard/src/controller/dashboard/status/Live.ts, plugins/plugin-codeflare-dashboard/src/controller/dashboard/status/states.ts, plugins/plugin-codeflare-dashboard/src/controller/env.ts
e.g. if we are limited in vertical space, prefer to show pods still Pulling images over pods that have announced they are done and Pulled also this improves the display of duplicate lines, rather just updating the timestamp
=> fix: use a priority heap to choose most important events to display

plugins/plugin-codeflare-dashboard/src/controller/dashboard/status/Live.ts
there's just too many events when running a large number of workers
=> fix: avoid events in dashboard UI for line

plugins/plugin-codeflare-dashboard/src/components/Dashboard/Grid.tsx, plugins/plugin-codeflare-dashboard/src/components/Dashboard/index.tsx
ink v3 doesn't render well when the window is narrowed, especially for boxes with borders. this removes the border from the header, and tightens up a few horizontal margins.
=> fix: improvements in dashboard for narrowing of window

package-lock.json, plugins/plugin-codeflare/package.json, tests/kind/run.sh, tests/self-test/self-test.yaml
- use websocat on the head node
- use ray job logs, on the head node, to synchronize with job completion
- avoid any use of stdin bindings on the client side
- continue avoiding websocat installation on the client side
=> fix: further improvements to ray log streaming

plugins/plugin-codeflare-dashboard/src/components/Top/index.tsx
this also has a few UI tweaks:
- trim box title to at most 34 chars
- use 0-gap between boxes
- improve selection UI for non-selected boxes
- try to keep the duration at a fixed length, to avoid reflows, e.g. 15m 9s -> 15m 10s
=> fix: top node selection UI is buggy

plugins/plugin-codeflare-dashboard/package.json
it turns out that `yoga-wasm-web` does something silly with the way it loads the wasm; rather than a simple `import('./yoga.wasm')` it does some gymnastics that include a `readFile`, thus assuming the wasm is a file, not a more general module. so this change adds a webpack rule that forces just yoga.wasm to be treated as a file resource.
=> fix: force yoga.wasm to be loaded as a file resource

package-lock.json, plugins/plugin-codeflare/package.json
* cpu utilization information may be bogus; switch to cgroup-based stats ([a409a7e](https://github.com/guidebooks/store/commit/a409a7ed556aed5265a95d7a1f7150da21030bbd))
* increase max log requests for app logs ([3d5ca5c](https://github.com/guidebooks/store/commit/3d5ca5cf46a849745c92d6bd5c07f8f0a49112f8))
* ray head wait-for-workers initContainer should retry if wait fails ([2ab27b6](https://github.com/guidebooks/store/commit/2ab27b6c8c27a6d567fd954aa3c0eb8a1b49abf4))
=> fix: improve cpu utilization metrics, and retry on ray head initContainer
