package-lock.json
package.json

i don't think we need that plugin in this client

chore: remove plugin-git

---

package-lock.json
plugins/plugin-madwizard/package.json

chore: bump to madwizard 0.8.6

---

package-lock.json
plugins/plugin-madwizard/package.json

picks up some bug fixes for export and support for gpu detection (via env var)

chore: bump madwizard to 0.8.7

---

package-lock.json
plugins/plugin-madwizard/package.json

this picks up shell.async support

chore: bump to madwizard 0.8.12

---

tests/plugin-madwizard/plan/plan.ts

macos seems to time out some times. try this.

test: increase playwright test timeout

---

package-lock.json
plugins/plugin-madwizard/package.json
plugins/plugin-madwizard/src/components/Guide.tsx
plugins/plugin-madwizard/src/components/Plan.tsx

picks up initial profile support

chore: bump to madwizard 0.9.12

---

package-lock.json
plugins/plugin-madwizard/package.json

picks up a fix in the cli guide display of suggestions

chore: bump to madwizard 0.10.2

---

bin/codeflare

fix: allow user to specify custom guidebook store via `-s` flag

---

package-lock.json
plugins/plugin-madwizard/package.json

fixes a race condition in expansion

chore: bump to madwizard 0.10.7

---

package-lock.json
plugins/plugin-madwizard/package.json

Picks up support for persisting choices after every choice is made.

chore: bump to madwizard 0.10.8

---

package-lock.json
package.json

picks up some underlying version bumps

chore: bump kui deps

---

.prettierignore
plugins/plugin-madwizard/src/components/Guide.tsx
plugins/plugin-madwizard/src/components/Plan.tsx
plugins/plugin-madwizard/src/plugin.ts
tests/plugin-madwizard/plan/inputs/1.spec.ts
tests/plugin-madwizard/plan/plan.ts

also add some exclusions to the prettierignore file, for test inputs and guidebook markdown

chore: reformatting updates

---

package-lock.json
package.json
plugins/plugin-client-default/config.d/notebooks.json
plugins/plugin-client-default/notebooks/dashboard-live.md
plugins/plugin-codeflare/src/controller/dashboard.ts
plugins/plugin-codeflare/web/scss/components/#Dashboard.scss#
plugins/plugin-codeflare/web/scss/components/Dashboard/_index.scss

This PR splits dashboard.md into an offline (dashboard.md) and live (dashboard-live.md) variant.
This PR also picks up some bug fixes from Kui.

chore: refinements to dashboard

---

package-lock.json
package.json
plugins/plugin-client-default/notebooks/dashboard.md

this leverages a small update to kui core to enable filtering out a json structure in a guidebook

feat: update dashboard to include env vars and application source

---

package-lock.json
package.json
plugins/plugin-client-default/notebooks/dashboard.md
plugins/plugin-client-default/src/index.tsx
plugins/plugin-codeflare/web/scss/components/Dashboard/_index.scss

also hide tab UI
also hide hamburger menu UI

feat: orient dashboard with a top-bottom layout

---

package-lock.json
package.json

notarization should be much faster now

chore: bump kui to pick up macos notarization update

---

plugins/plugin-codeflare/web/scss/components/Dashboard/_index.scss

editor background color in some themes

fix: contrast can be low in the dashboard

---

plugins/plugin-client-default/notebooks/dashboard-live.md
plugins/plugin-client-default/notebooks/dashboard-source.md
plugins/plugin-client-default/notebooks/dashboard-summary.md
plugins/plugin-client-default/notebooks/dashboard.md

This hopefully will alleviate some of the skew between the live and offline dashboards.

fix: update dashboard-live.md to use common bits from dashboard.md

---

plugins/plugin-client-default/notebooks/dashboard-live.md

Rather than use the default `-n 10`

feat: update live dashboard to use `tail -n 500`

---

plugins/plugin-client-default/notebooks/dashboard.md

some copy-paste bugs from the application source section

fix: dashboard kube events has bogus config

---

package-lock.json
plugins/plugin-madwizard/package.json

chore: bump to madwizard 0.10.14

---

package-lock.json
plugins/plugin-madwizard/package.json

This picks up cli guide output cleanup

chore: bump to madwizard 0.11.0

---

package-lock.json

Our fork was not being picked up

chore: re-generate package-lock to fix bug with minio deps

---

plugins/plugin-client-default/notebooks/dashboard.md
plugins/plugin-codeflare/src/components/Chart.tsx
plugins/plugin-codeflare/src/components/VmstatChart.tsx
plugins/plugin-codeflare/src/controller/charts/gpu.ts
plugins/plugin-codeflare/src/controller/charts/vmstat.ts
plugins/plugin-codeflare/src/lib/util.ts

some cleanup to refactor core charting into a base class BaseChart

feat: pod vmstat charts

---

plugins/plugin-client-default/config.d/style.json
plugins/plugin-client-default/notebooks/dashboard.md
plugins/plugin-codeflare/src/components/Chart.tsx
plugins/plugin-codeflare/web/scss/components/Dashboard/_index.scss

- changes aspect ratio of charts
- improve patternfly chart colors

feat: more dashboard tweaks, including using Patternfly4 Dark as default theme

---

plugins/plugin-codeflare/src/components/Chart.tsx

also a small bit of code cleanup in that area

fix: use slightly smaller stroke width in charts

---

plugins/plugin-codeflare/src/components/Chart.tsx
plugins/plugin-codeflare/src/components/GPUChart.tsx
plugins/plugin-codeflare/src/components/VmstatChart.tsx
plugins/plugin-codeflare/web/scss/components/Dashboard/Charts.scss

and some small adjustments around it (x axis labels, padding) to make this fit

feat: update dashboard charts to show 4 charts per row

---

package-lock.json
plugins/plugin-client-default/notebooks/dashboard-summary.md
plugins/plugin-codeflare/package.json
plugins/plugin-codeflare/src/components/Description.tsx
plugins/plugin-codeflare/src/controller/description.ts
plugins/plugin-codeflare/web/scss/components/Dashboard/Description.scss
plugins/plugin-codeflare/web/scss/components/Dashboard/_index.scss

feat: format summary as a patterfly DescriptionList

---

plugins/plugin-codeflare/web/scss/components/Dashboard/Charts.scss

fix: decrease padding around charts

---

plugins/plugin-client-default/src/CodeFlareWidget.tsx
plugins/plugin-client-default/src/index.tsx

and shift github icon to the lower right

fix: remove Made with Kui for now, replace with CodeFlareWidget

---

plugins/plugin-codeflare/src/components/Description.tsx
plugins/plugin-codeflare/src/controller/description.ts

also remove some lower-priority fields from the description list model, to clean up the UI a bit

chore: code cleanup in description command handler

---

plugins/plugin-codeflare/src/components/Chart.tsx
plugins/plugin-codeflare/src/components/Description.tsx
plugins/plugin-codeflare/web/scss/components/Dashboard/Charts.scss
plugins/plugin-codeflare/web/scss/components/Dashboard/Description.scss
plugins/plugin-codeflare/web/scss/components/Dashboard/_index.scss

fix: move dashboard charts to lower left

---

plugins/plugin-client-default/notebooks/dashboard.md
plugins/plugin-codeflare/src/components/Chart.tsx
plugins/plugin-codeflare/src/components/ChartGrid.tsx
plugins/plugin-codeflare/src/components/GPUChart.tsx
plugins/plugin-codeflare/src/components/VmstatChart.tsx
plugins/plugin-codeflare/src/controller/charts/LogRecord.ts
plugins/plugin-codeflare/src/controller/charts/all.tsx
plugins/plugin-codeflare/src/controller/charts/gpu.tsx
plugins/plugin-codeflare/src/controller/charts/vmstat.tsx

feat: update charts to lay out gpu and cpu side-by-side for a node

---

plugins/plugin-codeflare/src/controller/charts/all.tsx

so that nodes for which we have better information float to the top; better meaning "both cpu and gpu", otherwise "has only gpu", in last place "has only cpu"

fix: improve sort order of combined gpu/cpu chart set

---

plugins/plugin-client-default/notebooks/dashboard.md

fix: typo in dashboard.md results in Choices tab not appearing as expected

---

plugins/plugin-codeflare/src/components/Chart.tsx
plugins/plugin-codeflare/src/components/GPUChart.tsx
plugins/plugin-codeflare/src/components/VmstatChart.tsx
plugins/plugin-codeflare/src/controller/charts/all.tsx
plugins/plugin-codeflare/src/controller/charts/gpu.tsx
plugins/plugin-codeflare/src/controller/charts/timestamps.ts
plugins/plugin-codeflare/src/controller/charts/vmstat.tsx

we need to use a common time range (min, max) across the charts

fix: charts may have different y axis labels

---

plugins/plugin-codeflare/src/components/Chart.tsx
plugins/plugin-codeflare/src/components/GPUChart.tsx

this requires a change from voronoicontainer to cursorvoronoicontainer implementation
Fixes #173
Closes #190

feat: use fancy legend tooltips in charts

---

plugins/plugin-codeflare/web/scss/themes/Mirage.scss
plugins/plugin-codeflare/web/scss/themes/Onyx.scss
plugins/plugin-codeflare/web/scss/themes/Tuatara.scss

fix: several themes have poor contrast for "blue" colors

---

plugins/plugin-codeflare/web/scss/themes/Mirage.scss
plugins/plugin-codeflare/web/scss/themes/Tuatara.scss

mirage yellow
tuatara blue in inverted

fix: a few more coloring issues with themes

---

plugins/plugin-client-default/notebooks/dashboard.md
plugins/plugin-codeflare/src/components/Grid.tsx
plugins/plugin-codeflare/src/controller/events/Event.ts
plugins/plugin-codeflare/src/controller/events/Events.tsx
plugins/plugin-codeflare/src/controller/events/index.ts
plugins/plugin-codeflare/src/controller/events/kube.ts
plugins/plugin-codeflare/src/controller/events/torch.ts
plugins/plugin-codeflare/src/controller/index.ts
plugins/plugin-codeflare/web/scss/components/Dashboard/Grid.scss
plugins/plugin-codeflare/web/scss/components/Dashboard/_index.scss
tests/plugin-codeflare/dashboard/inputs/2/events/kubernetes.txt

feat: progress grid

---

plugins/plugin-codeflare/src/components/Terminal.tsx

this may save a bit on refreshes in the UI

fix: Terminal component should write initialContent before mounting

---

package-lock.json
package.json
plugins/plugin-codeflare/package.json
plugins/plugin-codeflare/src/components/Chart.tsx
plugins/plugin-codeflare/src/components/ComboChart.tsx
plugins/plugin-codeflare/src/components/GPUChart.tsx
plugins/plugin-codeflare/src/components/Terminal.tsx
plugins/plugin-codeflare/src/components/VmstatChart.tsx
plugins/plugin-codeflare/src/controller/charts/all.tsx
plugins/plugin-codeflare/src/controller/charts/gpu.tsx
plugins/plugin-codeflare/src/controller/charts/timestamps.ts
plugins/plugin-codeflare/src/controller/charts/vmstat.tsx
plugins/plugin-codeflare/src/controller/tailf.ts

This PR also does some cleanup of the components in all.tsx -> ComboChart.tsx

feat: update gpu/cpu charts to allow for live streaming of log records into the charts

---

plugins/plugin-client-default/notebooks/dashboard.md
plugins/plugin-codeflare/src/components/Description.tsx
plugins/plugin-codeflare/src/controller/description.ts
plugins/plugin-codeflare/web/scss/components/Dashboard/Description.scss
plugins/plugin-codeflare/web/scss/components/Dashboard/_index.scss

Also: vertical layout for description lists
Also: place Events at the top, and devote less space to the summary info

feat: update summary section to split into Summary and Workers

---

plugins/plugin-client-default/src/index.tsx

We should instead use more specific search capabilities, such as https://github.com/project-codeflare/codeflare-cli/pull/233

feat: disable the Kui Search component

---

plugins/plugin-codeflare/src/components/Grid.tsx
plugins/plugin-codeflare/src/controller/events/torch.ts
plugins/plugin-codeflare/web/scss/components/Dashboard/Grid.scss

added data fetch/uncompress events (magenta) and torch Evaluation events (purple)

feat: add torch Evaluation events to the UI

---

bin/codeflare

fix: bin/codeflare has an unquoted shell expression

---

package-lock.json
plugins/plugin-codeflare/package.json
plugins/plugin-codeflare/src/components/Chart.tsx

we should use a real memory pretty printer
Closes #208

fix: chart tooltips can show "0 Gi"

---

bin/codeflare
package-lock.json
plugins/plugin-codeflare/src/controller/attach.ts
plugins/plugin-codeflare/src/controller/dashboard.ts
plugins/plugin-codeflare/src/controller/index.ts
plugins/plugin-madwizard/package.json
plugins/plugin-madwizard/src/plugin.ts

Also add `codeflare db` as a synonym for `codeflare dashboard`.

feat: change `codeflare attach` to `codeflare dashboard --attach/-a`

---

package-lock.json
plugins/plugin-madwizard/package.json
plugins/plugin-madwizard/src/plugin.ts
plugins/plugin-madwizard/src/read.ts

this adds initial support for the profile api. no user-visible changes yet.

chore: bump to madwizard 0.14.1

---

package-lock.json
plugins/plugin-madwizard/package.json

this adds initial support for the profile api. no user-visible changes yet.

chore: bump to madwizard 0.14.2

---

package-lock.json
plugins/plugin-codeflare/src/controller/attach.ts
plugins/plugin-codeflare/src/controller/description.ts
plugins/plugin-madwizard/package.json

Also updates the related dashboard commands to improve handling of filepaths with spaces.

fix: update codeflare attach to use logdir created by the guidebook

---

package-lock.json
package.json
plugins/plugin-client-default/config.d/style.json
plugins/plugin-client-default/notebooks/welcome.md
plugins/plugin-client-default/src/index.tsx
plugins/plugin-client-default/web/scss/guidebooks/welcome.scss
plugins/plugin-codeflare/src/controller/dashboard.ts
plugins/plugin-codeflare/src/controller/description.ts
plugins/plugin-codeflare/src/controller/index.ts
plugins/plugin-codeflare/src/controller/profile/get.tsx
plugins/plugin-codeflare/src/controller/run/get.tsx
plugins/plugin-codeflare/src/tray.ts
plugins/plugin-codeflare/web/scss/components/Welcome/_index.scss

Show this, instead of a blank terminal window when opening a new window.
Also update the tray menu to open this new popup rather than visiting the codeflare home page, when clicking the first menu item.
The design here is still HIGHLY a work in progress
.

feat: initial "welcome" popup

---

package-lock.json
package.json
plugins/plugin-codeflare/src/controller/guide.ts
plugins/plugin-codeflare/src/controller/index.ts
plugins/plugin-codeflare/src/preload.ts
plugins/plugin-codeflare/src/tray/main.ts
plugins/plugin-codeflare/src/tray/profiles.ts
plugins/plugin-codeflare/src/tray/renderer.ts
plugins/plugin-codeflare/src/tray/window.ts

This PR also includes a bit of code cleanup/refactoring, placing the tray logic under a subdirectory.

feat: initial Boot/Shutdown options from tray menu

---

plugins/plugin-codeflare/src/tray/menus/index.ts

feat: small rearrangement to order in tray menu

---

plugins/plugin-client-default/notebooks/hello.md
plugins/plugin-client-default/notebooks/runs.md
plugins/plugin-client-default/src/index.tsx
plugins/plugin-codeflare/src/controller/index.ts
plugins/plugin-codeflare/src/controller/run/get.ts
plugins/plugin-codeflare/src/tray/menus/index.ts
plugins/plugin-codeflare/src/tray/menus/profiles/dashboards/codeflare.ts
plugins/plugin-codeflare/src/tray/menus/profiles/dashboards/open.ts
plugins/plugin-codeflare/src/tray/menus/profiles/index.ts
plugins/plugin-codeflare/src/tray/menus/profiles/runs.ts
plugins/plugin-codeflare/src/tray/menus/profiles/status.ts
plugins/plugin-codeflare/src/tray/menus/profiles/tasks.ts
plugins/plugin-codeflare/src/tray/watchers/profile/run.ts
plugins/plugin-codeflare/web/scss/components/Hello/_index.scss

This PR also rejiggers the "hello.md" guidebook. This needs a lot of work. The goal is to introduce codeflare and point people to next steps.
https://user-images.githubusercontent.com/4741620/180670624-a2a859fc-128f-4880-97a1-f61af3cf9dce.mp4

feat: add tensorboard support to tray menu

---

plugins/plugin-codeflare/src/tray/menus/profiles/runs.ts
plugins/plugin-codeflare/src/tray/watchers/profile/list.ts
plugins/plugin-codeflare/src/tray/watchers/profile/run.ts

we need to limit the depth of the chokidar watch

fix: tray runs watcher reports sub-files in the list

---

package-lock.json
plugins/plugin-madwizard/package.json

https://github.com/guidebooks/madwizard/pull/377

chore: bump to madwizard 0.15.13 to pick up profile bug fix

---

bin/codeflare

We are not currently maintaining the UI components Plan and Guide.

fix: disable codeflare -u for now

---

plugins/plugin-codeflare/src/tray/watchers/profile/run.ts

- re: garbage timestamps, we are not setting `alwaysStat=true`. by default, chokidar only reports file stats for the initial scan
- re: garbage entries, sigh. i can't figure out how to configure chokidar to show only top-level directory entries, of the specified watch directory; this PR has some fixes for that, but not ideal ones.

fix: tray menu run watcher reports garbage timestamps and garbage entries

---

plugins/plugin-client-default/notebooks/hello.md
plugins/plugin-codeflare/src/components/CodeFlareGallery.tsx
plugins/plugin-codeflare/src/controller/hello.ts
plugins/plugin-codeflare/src/controller/index.ts
plugins/plugin-codeflare/src/controller/profile/get.tsx
plugins/plugin-codeflare/web/scss/components/Hello/_index.scss

- add new appliances section
- change scss to split horizontally the three sections

hello page layout

---

plugins/plugin-client-default/notebooks/hello.md
plugins/plugin-codeflare/src/controller/index.ts
plugins/plugin-codeflare/src/controller/profile/get.tsx
plugins/plugin-codeflare/web/scss/components/Hello/_index.scss

1) fixed tile text color in dark themes (not visible)
2) font size in tiles too small
3) maximized content
4) switch to using flex layout for profiles
5) inverse colors for gallery stripe

fix: some UI refinements to the Profiles section of the Hello components

---

package-lock.json
plugins/plugin-madwizard/package.json

https://github.com/guidebooks/madwizard/pull/386

fix: bump to madwizard 0.18.1 to pick up dashdash fixes

---

package-lock.json
package.json
plugins/plugin-client-default/notebooks/hello.md
plugins/plugin-codeflare/src/components/Terminal.tsx
plugins/plugin-codeflare/src/controller/index.ts
plugins/plugin-codeflare/src/controller/terminal.tsx

Plus updates to the Terminal component to support user input and resize events flowing back to the controller.

feat: add `codeflare terminal` command

---

plugins/plugin-client-default/config.d/style.json
plugins/plugin-client-default/notebooks/hello.md
plugins/plugin-codeflare/src/controller/index.ts
plugins/plugin-codeflare/src/controller/profile/get.tsx
plugins/plugin-codeflare/src/tray/menus/index.ts
plugins/plugin-codeflare/web/scss/components/Cast/_index.scss
plugins/plugin-codeflare/web/scss/components/Dashboard/_index.scss
plugins/plugin-codeflare/web/scss/components/Hello/_index.scss

And an improved aspect ratio for the window.

feat: use side-by-side layout for hello

---

plugins/plugin-client-default/notebooks/hello.md
plugins/plugin-codeflare/src/controller/profile/get.tsx
plugins/plugin-codeflare/web/scss/components/Hello/_index.scss

Also, improved grid layout for profiles, to get them to wrap better in smaller spaces.

fix: wordsmithing of hello.md plus always show profiles section

---

plugins/plugin-codeflare/src/controller/profile/get.tsx
plugins/plugin-codeflare/src/tray/menus/profiles/index.ts
plugins/plugin-codeflare/src/tray/watchers/profile/list.ts

We already had this profile watching logic for the tray menu. This PR updates the profiles UI component to use the same.

feat: update profiles ui component to use profile watching logic

---

package-lock.json
plugins/plugin-client-default/notebooks/hello.md
plugins/plugin-codeflare/src/components/ProfileExplorer.tsx
plugins/plugin-codeflare/src/components/RestartableTerminal.tsx
plugins/plugin-codeflare/src/components/SelectedProfileTerminal.tsx
plugins/plugin-codeflare/src/controller/profile/get.tsx
plugins/plugin-codeflare/src/controller/terminal.tsx
plugins/plugin-codeflare/src/tray/watchers/profile/list.ts
plugins/plugin-madwizard/package.json

Including having the `codeflare` terminal pay attention to the selected profile

feat: improved support for selecting profiles from the profile explorer

---

plugins/plugin-codeflare/src/components/ProfileExplorer.tsx
plugins/plugin-codeflare/src/components/RestartableTerminal.tsx
plugins/plugin-codeflare/src/components/SelectedProfileTerminal.tsx

I don't think this PR fixes all of the issues, but it's a lot more stable now.

fix: ProfileExplorer UI can be racy w.r.t selections and initial render

---

plugins/plugin-codeflare/src/tray/watchers/profile/status.ts

if the watcher subprocess exits, we should restart it

fix: profile status watcher can get stuck, never updating

---

plugins/plugin-codeflare/src/components/ProfileExplorer.tsx

until we implement the onclick handler

fix: disable New Profile tile for now

---

plugins/plugin-codeflare/src/components/DashboardSelect.tsx
plugins/plugin-codeflare/src/components/ProfileExplorer.tsx
plugins/plugin-codeflare/src/components/ProfileSelect.tsx
plugins/plugin-codeflare/src/controller/profile/actions.ts
plugins/plugin-codeflare/web/scss/components/ProfileExplorer/_index.scss

Note: In this PR, some of the content is still placeholder text. e.g. Status: pending

feat: enhance ui profiles/appliances section

---

plugins/plugin-codeflare/src/components/ProfileExplorer.tsx
plugins/plugin-codeflare/src/components/ProfileSelect.tsx

fix: implement profile selection change in new ProfileExplorer

---

plugins/plugin-client-default/config.d/style.json
plugins/plugin-codeflare/src/controller/index.ts
plugins/plugin-codeflare/src/controller/profile/actions.ts
plugins/plugin-codeflare/src/tray/menus/index.ts

This PR also cleans up the many random hard-coded uses of the desired initial window width and height.

fix: cheat and make default window width slightly wider to fix current guidebook content

---

package-lock.json
plugins/plugin-client-default/notebooks/hello.md
plugins/plugin-codeflare/package.json
plugins/plugin-codeflare/src/components/ProfileExplorer.tsx
plugins/plugin-codeflare/src/components/Terminal.tsx
plugins/plugin-codeflare/src/controller/index.ts
plugins/plugin-codeflare/src/controller/terminal.tsx
plugins/plugin-codeflare/web/scss/components/ProfileExplorer/_index.scss

Also
- places the profile selector in the profile card header
- refactors to have a separate ProfileCard component

feat: update codeflare explorer to use adjustable split pane for cli portion

---

package-lock.json
package.json

to pick up an electron bump (18.3.7) and a terminal zoom bug fix

chore: bump kui dependencies

---

deploy/self-test/Dockerfile
deploy/self-test/run.sh
deploy/self-test/self-test.sh
deploy/self-test/self-test.yaml
package.json
tests/kind/inputs/ray-tune-tutorial/README.md
tests/kind/inputs/ray-tune-tutorial/main.py
tests/kind/inputs/ray-tune-tutorial/requirements.txt
tests/kind/profiles/gpu1/keep-it-simple
tests/kind/profiles/gpu1/mcad-coscheduler
tests/kind/profiles/gpu1/mcad-default
tests/kind/profiles/gpu1/mcad-preinstalled
tests/kind/profiles/gpu1/ray-autoscaler
tests/kind/run.sh

This adds support for tests that launch jobs from within a kubernetes cluster.
```shell
./deploy/self-test/run.sh
```
this will launch a Job in your current context+namespace that 
1) git clones the latest remote version of your current local branch (make sure to commit and push before running another test)
2) fires off a given set of "variants" (non-gpu, gpu1, etc. to be found in ./tests/kind/profiles/*
3) for each variant, it does the same test run that we do now for the `kind.yml`

test: docker image for self-testing codeflare in a pod

---

.github/workflows/kind.yml
bin/codeflare
deploy/log-aggregator/wait-for.sh
package-lock.json
package.json
plugins/plugin-client-default/notebooks/dashboard.md
plugins/plugin-codeflare/src/controller/attach.ts
plugins/plugin-codeflare/src/controller/dashboard.ts
plugins/plugin-codeflare/src/controller/description.ts
plugins/plugin-codeflare/src/controller/index.ts
plugins/plugin-codeflare/src/tray/menus/profiles/log-aggregator.ts
plugins/plugin-codeflare/src/tray/menus/profiles/tasks.ts
plugins/plugin-madwizard/package.json
tests/kind/profiles/gpu1/keep-it-simple
tests/kind/profiles/gpu1/mcad-coscheduler
tests/kind/profiles/gpu1/mcad-default
tests/kind/profiles/gpu1/mcad-preinstalled
tests/kind/profiles/gpu1/ray-autoscaler
tests/kind/profiles/non-gpu1/keep-it-simple
tests/kind/profiles/non-gpu1/mcad-coscheduler
tests/kind/profiles/non-gpu1/mcad-default
tests/kind/profiles/non-gpu1/mcad-preinstalled
tests/kind/profiles/non-gpu1/ray-autoscaler
tests/kind/profiles/non-gpu2/keep-it-simple
tests/kind/profiles/non-gpu3/keep-it-simple
tests/kind/run.sh

Also adds tests coverage for log aggregator.

fix: fixes for broken log aggregator

---

package.json

this will show us the output of our electron builds.

fix: run the release-it scripts in verbose mode

---

plugins/plugin-codeflare/src/controller/catchall.ts
plugins/plugin-codeflare/src/tray/menus/profiles/log-aggregator.ts
plugins/plugin-codeflare/src/tray/menus/profiles/tasks.ts
plugins/plugin-madwizard/src/plugin.ts

This PR also updates the Advanced tray menu to add a Start Log Aggregator

fix: pin version of log aggregator to version of codeflare

---

.github/workflows/self-test.yml
deploy/self-test/Dockerfile
deploy/self-test/run.sh
deploy/self-test/self-test.sh
deploy/self-test/self-test.yaml
package.json
tests/kind/run.sh
tests/kind/values.sh

i.e. this provides the capability for codeflare to launch itself as a Job within a chosen cluster

feat: improved self-test capability (launch codeflare tests such that they run within the cluster)

---

README.md
docs/development/README.md

This moves the dev docs into docs/development

doc: refresh top-level README

---

deploy/self-test/roberta/1gpu/once.yaml
deploy/self-test/roberta/1gpu/periodic.yaml
deploy/self-test/self-test.sh
docs/self-test/roberta/README.md

See docs/self-test/roberta/README.md for details

chore: add slack messaging capability to the self-test.sh script

---

deploy/self-test/roberta/1gpu/once.yaml
deploy/self-test/roberta/1gpu/periodic.yaml
deploy/self-test/roberta/1gpu/resume.sh
deploy/self-test/roberta/1gpu/suspend.sh
deploy/self-test/self-test.sh
docs/self-test/roberta/README.md

Also not the correct channel field in the payload.
This PR adds some helpers, resume.sh and suspend.sh, on the periodic task.

fix: roberta self-test was not base64-decoding slack secrets

---

package-lock.json
plugins/plugin-madwizard/package.json

https://github.com/guidebooks/store/pull/356

fix: bump @guidebook/store to 0.6.5 to pick up roberta env var fixes

---

package-lock.json
plugins/plugin-madwizard/package.json

We have no tests for ray-local.

feat: bump to @guidebooks/store 0.12.0 to pick up no-ray-local breaking change

---

plugins/plugin-codeflare/src/controller/guide.ts
plugins/plugin-codeflare/src/controller/respawn.ts
plugins/plugin-codeflare/src/controller/terminal.tsx
plugins/plugin-codeflare/src/tray/watchers/profile/status.ts

Our logic for finding the "app path" was incomplete.

fix: some variants of launching production builds can result in infinite loops and bad spawn paths

---

plugins/plugin-codeflare/src/tray/watchers/profile/status.ts

For some reason, a normal SIGTERM is not sufficing to clean up the watcher subprocesses we spawned.

fix: after exit codeflare UI leaves dangling watcher processes

---

plugins/plugin-codeflare/src/components/ProfileExplorer.tsx
plugins/plugin-codeflare/src/tray/watchers/profile/status.ts
plugins/plugin-codeflare/web/scss/components/ProfileExplorer/_index.scss

feat: add status dropdown with watcher support

---

package-lock.json
plugins/plugin-madwizard/package.json

see https://github.com/guidebooks/store/pull/396

fix: pin openshift to 4.10.33 (from @guidebooks/store 0.12.6)

---

bin/codeflare
package-lock.json
plugins/plugin-madwizard/package.json
tests/plugin-madwizard/plan/inputs/1.spec.ts
tests/plugin-madwizard/plan/inputs/2.spec.ts
tests/plugin-madwizard/plan/inputs/3.spec.ts
tests/plugin-madwizard/plan/inputs/4.spec.ts
tests/plugin-madwizard/plan/inputs/6.spec.ts
tests/plugin-madwizard/plan/inputs/7.spec.ts

Reverts project-codeflare/codeflare-cli#571

Revert "fix: bump to madwizard 0.23.4 to pick up 'validate' invalidation fixes"

---

package-lock.json
package.json
plugins/plugin-codeflare/src/components/ProfileExplorer.tsx
plugins/plugin-codeflare/web/scss/components/ProfileExplorer/_index.scss

1) use a TreeView
2) show actual data! (previously we had hard-coded garbage data)

feat: updated UI for ProfileExplorer

---

package-lock.json
plugins/plugin-madwizard/package.json
tests/kind/profiles/gpu1/keep-it-simple
tests/kind/profiles/non-gpu1/keep-it-simple
tests/kind/profiles/non-gpu1/mcad-coscheduler
tests/kind/profiles/non-gpu1/mcad-default
tests/kind/profiles/non-gpu1/mcad-preinstalled
tests/kind/profiles/non-gpu1/ray-autoscaler
tests/kind/profiles/non-gpu2/keep-it-simple
tests/kind/profiles/non-gpu3/keep-it-simple
tests/kind/profiles/non-gpu4/keep-it-simple
tests/kind/profiles/roberta-1gpu/keep-it-simple

https://github.com/guidebooks/store/pull/407

fix: bump to @guidebooks/store 0.14.1 to pick up ns-with-context fix

---

package-lock.json
plugins/plugin-codeflare/src/components/DashboardSelect.tsx
plugins/plugin-codeflare/src/components/ProfileExplorer.tsx
plugins/plugin-codeflare/src/components/SelectedProfileTerminal.tsx
plugins/plugin-codeflare/src/controller/terminal.tsx
plugins/plugin-codeflare/web/scss/components/ProfileExplorer/_index.scss
plugins/plugin-madwizard/package.json
plugins/plugin-madwizard/src/plugin.ts

This PR also leverages the "interactive for" feature in madwizard 1.1.0

fix: update ProfileExplorer to allow "editing" of aspects of the profile

---

plugins/plugin-codeflare/src/components/ProfileExplorer.tsx

This PR also adds some more meta rules.

fix: ProfileExplorer should sort the tree nodes to offer a consistent ordering

---

plugins/plugin-codeflare/src/components/ProfileExplorer.tsx
plugins/plugin-codeflare/web/scss/components/Dashboard/Description.scss
plugins/plugin-codeflare/web/scss/components/ProfileExplorer/_index.scss

This saves a bunch of vertical space.

fix: in ProfileExplorer, move actions to kebab and out of footer

---

package-lock.json
plugins/plugin-codeflare/src/components/ProfileExplorer.tsx
plugins/plugin-madwizard/package.json

This PR bumps us to madwizard@1.6.0 to pick up the `Profiles.createIfNeeded()` API, and udpates ProfileExplorer to use it. It also includes some minor code cleanup around this.

fix: UI hangs with spinners for first-time users

---

plugins/plugin-codeflare/src/components/RestartableTerminal.tsx
plugins/plugin-codeflare/src/components/Terminal.tsx
plugins/plugin-codeflare/src/controller/terminal.tsx

This also restores the default terminal font size.

feat: allow terminal search feature to be disabled

---

package-lock.json
plugins/plugin-madwizard/package.json

https://github.com/guidebooks/store/pull/416

fix: bump to @guidebooks/store@0.15.0 to pick up s3fs pvc fix

---

package-lock.json
plugins/plugin-madwizard/package.json

https://github.com/guidebooks/store/pull/417

fix: update to @guidebooks/store@0.15.1 to pick up aws/auth fix

---

package-lock.json
plugins/plugin-madwizard/package.json

https://github.com/guidebooks/store/pull/418

fix: bump to @guidebooks/store@0.15.2 to pick up more pvc fixes

---

package-lock.json
plugins/plugin-madwizard/package.json

https://github.com/guidebooks/madwizard/pull/462

fix: bump to madwizard@1.6.5 to pick up updated Choice messaging

---

package-lock.json
package.json

e.g. guidebook descriptions with more than one terminal link

fix: bump kui to pick up fix for multi-link markdown

---

package-lock.json
package.json

https://github.com/kubernetes-sigs/kui/pull/9103

fix: bump kui to pick up fix for markdown terminal links

---

plugins/plugin-codeflare/src/components/ProfileExplorer.tsx
plugins/plugin-codeflare/web/scss/components/Ask/_index.scss

Also increase max-width of Ask

fix: ProfileExplorer has extra spacing to the right of New button

---

package-lock.json
plugins/plugin-codeflare/package.json
plugins/plugin-codeflare/src/components/AskingTerminal.tsx
plugins/plugin-codeflare/src/components/RestartableTerminal.tsx
plugins/plugin-codeflare/src/components/Terminal.tsx
plugins/plugin-codeflare/src/controller/terminal.tsx
plugins/plugin-madwizard/package.json

Instead, display "Logs will appear here".
Also, use 14px font size in terminal, now that it isn't a main source of user interaction.

fix: update madwizard to not show guidebook title in terminal section

---

package-lock.json
plugins/plugin-codeflare/src/tray/menus/profiles/tasks.ts
plugins/plugin-codeflare/src/tray/watchers/profile/active-runs.ts
plugins/plugin-codeflare/src/tray/watchers/profile/status.ts
plugins/plugin-madwizard/package.json

The tray menu was not cleaning up properly.

fix: multiple fixes for excessive cpu consumption

---

plugins/plugin-codeflare/src/components/Ask.tsx

user typed updates would not register

fix: regression in user updates to form inputs

---

package-lock.json
plugins/plugin-madwizard/package.json

https://github.com/guidebooks/madwizard/pull/574
https://github.com/guidebooks/store/pull/481

fix: bump madwizard 2.5.2 to pick up multiselect fix

---

.github/workflows/cli.yml
package-lock.json
package.json
plugins/plugin-codeflare/package.json

also bump to store 2.0.0 to pick up image-pull validation hang fix
also improved filtering of kube namespaces

fix: bump plugin-madwizard to pick up parsing bug in raw mode with madwizard

---

package-lock.json
plugins/plugin-codeflare/package.json

https://github.com/guidebooks/store/pull/496
https://github.com/guidebooks/store/pull/497

fix: bump @guidebook/store 2.0.1 -> 2.0.2

---

package-lock.json
plugins/plugin-codeflare/package.json

This should give us improved support for shutting down the ray cluster on ctrl+c

feat: bump to madwizard@4.3.0 and @guidebooks/store@2.1.0 to pick up finally support

---

package-lock.json
package.json
plugins/plugin-codeflare/package.json

also bump @guidebooks/store@2.2.9 to pick up fix for ctrl+c killing of helm cluster prior to getting a cluster name

fix: bump madwziard@5.0.6 to pick up ctrl+c fixes

---

package-lock.json
plugins/plugin-codeflare/package.json

also bump madwizard@5.0.7 to pick up "undefined" on ctrl+c

fix: bump @guidebooks/store@2.2.10 to pick up s3fs mounting on ray head

---

package-lock.json
plugins/plugin-codeflare/package.json
tests/kind/profiles/gpu1/keep-it-simple
tests/kind/profiles/non-gpu1/keep-it-simple
tests/kind/profiles/non-gpu1/mcad-coscheduler
tests/kind/profiles/non-gpu1/mcad-default
tests/kind/profiles/non-gpu1/mcad-preinstalled
tests/kind/profiles/non-gpu1/ray-autoscaler
tests/kind/profiles/non-gpu2/keep-it-simple
tests/kind/profiles/non-gpu3/keep-it-simple
tests/kind/profiles/non-gpu4/keep-it-simple
tests/kind/profiles/roberta-1gpu/keep-it-simple

also bump madwizard@5.0.8 to pick up improved ctrl+c handling during active forms

fix: bump @guidebook/store@2.3.0 to pick up support for specifying ray ephemeral storage

---

package-lock.json
package.json
plugins/plugin-codeflare/package.json

Also bump madwizard to pick up security fix.

fix: bump @guidebooks/store to pick up improved ray cluster name

---

package-lock.json
plugins/plugin-codeflare/package.json

fix: helm chart names may fail if they have uppercase chars

---

package-lock.json
plugins/plugin-codeflare/package.json

fix: improve formatting of kubernetes event stream

---

package-lock.json
plugins/plugin-codeflare/package.json
tests/kind/profiles/gpu1/keep-it-simple
tests/kind/profiles/non-gpu1/keep-it-simple
tests/kind/profiles/non-gpu1/mcad-coscheduler
tests/kind/profiles/non-gpu1/mcad-default
tests/kind/profiles/non-gpu1/mcad-preinstalled
tests/kind/profiles/non-gpu1/ray-autoscaler
tests/kind/profiles/non-gpu2/keep-it-simple
tests/kind/profiles/non-gpu3/keep-it-simple
tests/kind/profiles/non-gpu4/keep-it-simple

https://github.com/guidebooks/store/pull/602
Also minor update to madwizard to improve alignment of form elements https://github.com/guidebooks/madwizard/pull/666

feat: allow BYOC to specify command line prefix

---

package-lock.json
plugins/plugin-codeflare/package.json

Also improved visibility of RAY_ADDRESS message

fix: improved vmstat streaming on linux

---

package-lock.json
plugins/plugin-codeflare/package.json

https://github.com/guidebooks/store/pull/610

fix: vmstats were using `sed -l` in a way that only made sense on BSD sed

---

package-lock.json
plugins/plugin-codeflare/package.json

also remove unnecessary mention of ray in namespace choice this includes initial support from madwizard for dynamic expansion into a multiselect

fix: torchx priority support

---

package-lock.json
plugins/plugin-codeflare/package.json
tests/kind/profiles/non-gpu1/keep-it-simple
tests/kind/profiles/non-gpu1/mcad-coscheduler
tests/kind/profiles/non-gpu1/mcad-default
tests/kind/profiles/non-gpu1/mcad-preinstalled
tests/kind/profiles/non-gpu1/ray-autoscaler
tests/kind/profiles/non-gpu2/keep-it-simple
tests/kind/profiles/non-gpu3/keep-it-simple
tests/kind/profiles/non-gpu4/keep-it-simple
tests/kind/profiles/non-gpu5/keep-it-simple
tests/kind/profiles/non-gpu6/keep-it-simple
tests/kind/profiles/non-gpu6/mcad-default
tests/kind/run.sh

this allows fixing: codeflare logs when late-attaching may not stream out gpu utilization
BREAKING CHANGE: this changes the structure of the ray form; tests may need updates. Also, any automated -y runs will require an update.

feat: update ray resources to match the newer/cleaner torchx resources form

---

package-lock.json
plugins/plugin-codeflare/package.json

BREAKING CHANGE: this updates s3/choose/bucket from single-select to multi-select, which may require re-selecting this choice

feat: support for selecting multiple s3 buckets to be mounted

---

package-lock.json
package.json
plugins/plugin-codeflare/package.json

this picks up a major bump in madwizard, correspondng to the removal of the `ray-submit` intrinsic

feat: bump to madwizard@7 to pick up multiselect autocomplete

---

package-lock.json
package.json

Reverts project-codeflare/codeflare-cli#844

Revert "fix: add missing `dotenv` dev dependence, for building production images"

---

package-lock.json
plugins/plugin-codeflare/package.json
tests/kind/profiles/non-gpu1/mcad-coscheduler.arm64
tests/kind/profiles/non-gpu1/mcad-coscheduler.x86_64
tests/kind/profiles/non-gpu1/mcad-default.arm64
tests/kind/profiles/non-gpu1/mcad-default.x86_64
tests/kind/profiles/non-gpu1/mcad-preinstalled.x86_64

also picks up mcad resource adjustments to improve test stability

feat: do not automatically bring down cluster on ctrl+c

---

package-lock.json
package.json
plugins/plugin-codeflare-dashboard/package.json
plugins/plugin-codeflare/package.json

laptop suspension and ctrl+z would oddly kill jobs

fix: pick up improved signal handling fixes from store and madwizard

---

package-lock.json
plugins/plugin-codeflare-dashboard/src/controller/dashboard/grids.ts
plugins/plugin-codeflare-dashboard/src/controller/dashboard/index.ts
plugins/plugin-codeflare-dashboard/src/controller/dashboard/kinds.ts
plugins/plugin-codeflare-dashboard/src/controller/dashboard/themes/utilization.ts
plugins/plugin-codeflare-dashboard/src/controller/dashboard/utilization.tsx
plugins/plugin-codeflare-dashboard/src/controller/dump.ts
plugins/plugin-codeflare/package.json

this also adjusts the utilization colors so that lower utilizations get less saturated colors, and higher utilizations get more saturated colors

fix: add gpu stats to dashboard

---

package-lock.json
plugins/plugin-codeflare-dashboard/package.json
plugins/plugin-codeflare/package.json

this also removes some leftover debugging output

fix: torchx install fails on zsh

---

package-lock.json
plugins/plugin-codeflare/package.json

https://github.com/guidebooks/store/pull/719

fix: torchx log output improvements

---

package-lock.json
plugins/plugin-codeflare/package.json

https://github.com/guidebooks/store/pull/722

fix: torchx captured logs may not include Succeeded/Failed events

---

plugins/plugin-codeflare-dashboard/src/controller/dashboard/status/Live.ts

fix: lines output was showing least interesting events

---

package-lock.json
plugins/plugin-codeflare/package.json

- wait till running was not waiting for all workers
- improved messaging while waiting
- memory utilization events were not properly prefixed with pod/

fix: torchx wait-till-running fixes

---

plugins/plugin-codeflare-dashboard/src/components/Dashboard/index.tsx
plugins/plugin-codeflare-dashboard/src/components/Dashboard/types.ts
plugins/plugin-codeflare-dashboard/src/controller/dashboard/status/Live.ts

also improve handling of timestamps in log lines

fix: strip node name from events and log lines

---

plugins/plugin-codeflare-dashboard/src/components/Top/Group.ts
plugins/plugin-codeflare-dashboard/src/components/Top/Header.tsx
plugins/plugin-codeflare-dashboard/src/components/Top/JobBox.tsx
plugins/plugin-codeflare-dashboard/src/components/Top/index.tsx
plugins/plugin-codeflare-dashboard/src/components/Top/types.ts
plugins/plugin-codeflare-dashboard/src/controller/dashboard/top.ts

plus some refactoring of Top into Header and JobBox

fix: add cluster and namespace to Top ui

---

package-lock.json
plugins/plugin-codeflare/package.json

https://github.com/guidebooks/store/pull/760

fix: improve custodian memory requests for larger jobs
